version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
    ports:
      - "8000:5432"